import type { Metadata } from "next";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Saurus Admin",
  description: "Generated by Saurus Admin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body style={{ height: "100vh" }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
